# Generated by Django 4.2.6 on 2023-10-19 04:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jet", "0001_squashed_0004_auto_20201228_1802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="pinnedapplication",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
