# Generated by Django 4.2.8 on 2023-12-07 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0002_alter_notemodel_note_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notemodel",
            old_name="is_pinned",
            new_name="is_trash",
        ),
    ]
